### ISSUE TITLE
HTTP Basic Auth profile?

### ISSUE THREAD

**Issue by edsu** [webrecorder/browsertrix-crawler#168]
Is it possible to crawl a site that has had HTTP Basic Authentication turned on? When I try to create a profile I get an error:

```
docker run -p 9222:9222 -p 9223:9223 -v $PWD/profiles:/output/ -it webrecorder/browsertrix-crawler create-login-profile --interactive --url "http://www.buffon.cnrs.fr"
Launching XVFB
loading
/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:225
                    ? new Error(`${response.errorText} at ${url}`)
                      ^

Error: net::ERR_INVALID_AUTH_CREDENTIALS at http://www.buffon.cnrs.fr
    at navigate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:225:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Frame.goto (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:195:21)
    at async Page.goto (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:1155:16)
    at async main (/app/create-login-profile.js:161:3)
```

Then I tried to create a profile by starting at one place and then navigating to the desired location. I see in the devtools console that a HTTP 401 response has been sent, but the popup to log in does not appear.

<img width="1647" alt="Screen Shot 2022-09-22 at 11 35 27 AM" src="https://user-images.githubusercontent.com/33829/191790627-74861a8b-a272-4698-8b67-52f7f69a0921.png">

**Comment by edsu** [comment]
I think I figured out a work-around for profile creation by using the [username/password in the URL](https://danq.me/2021/09/07/http-basic-auth-urls/) for example:

```
docker run -p 9222:9222 -p 9223:9223 -v $PWD/profiles:/output/ -it webrecorder/browsertrix-crawler create-login-profile --interactive --url "http://username:password@www.buffon.cnrs.fr/"
```

But using the resulting profile results in browsertrix-crawler hanging on startup indefintely after printing:

```
With Browser Profile: /crawls/profiles/buffon.tar.gz
```

**Comment by edsu** [comment]
I don't think that the Basic Auth credentials are stored in the profile and that puppeteer will need to be [started](https://pptr.dev/api/puppeteer.page.authenticate/) up with the credentials that are supplied on the command line. I can work on a small PR for this I think.

**Comment by justarmadillo** [comment]
> ```
> docker run -p 9222:9222 -p 9223:9223 -v $PWD/profiles:/output/ -it webrecorder/browsertrix-crawler create-login-profile --interactive --url "http://username:password@www.buffon.cnrs.fr/"
> ```
when I do this method, the following error results
![image](https://user-images.githubusercontent.com/10810222/203843695-662a5c8c-a5ec-4251-bb80-5251cb681c76.png)

**Comment by edsu** [comment]
@justarmadillo it looks like something might be wrong with the host name in your URL?  Unfortunately it doesn't seem to help to create the profile this way anyway. I noticed that the latest browsertrix-crawler is able to create a profile interactively where you can respond to the username/password prompt. But using the generated profile doesn't seem to allow crawl using the username/password :-(

**Comment by edsu** [comment]
I don't believe this is still relevant and it is showing up as assigned to me, and I don't have the ability to unsubscribe -- so I am closing.
