### ISSUE TITLE
Can't create browser profile

### ISSUE THREAD

**Issue by justarmadillo** [webrecorder/browsertrix-crawler#192]
When I execute this command to  create a username/password profile

docker run -v $PWD/crawls/profiles:/crawls/profiles -it webrecorder/browsertrix-crawler create-login-profile --url "example.com/login"

 I get this error:

```
loading
/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:225
                    ? new Error(`${response.errorText} at ${url}`)
                      ^
Error: net::ERR_NAME_NOT_RESOLVED at https://example.com/login
    at navigate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:225:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Frame.goto (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:195:21)
    at async Page.goto (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:1155:16)
    at async main (/app/create-login-profile.js:161:3)

```
here in the code I replaced the website that I used with example.com
Any solution or alternative method  to login to my desired website or a method to inject cookies ?

**Comment by justarmadillo** [comment]
even when I use interactive profile creation, the same error 

![image](https://user-images.githubusercontent.com/10810222/203920595-7b505d53-ad93-4930-9fa4-cb61c596835c.png)

**Comment by justarmadillo** [comment]
Solved my issue
changed my DNS to google's dns on windows.
