### ISSUE TITLE
Openshift: Browser cannot be launched error

### ISSUE THREAD

**Issue by DriesVanbilloen** [webrecorder/browsertrix-crawler#199]
We are running on an Openshift environment that does not run as admin. When triggering a crawl, we get the following error:

`Error: Unable to launch browser, error message: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1036745 is guaranteed to work.
at Cluster.init (/app/node_modules/puppeteer-cluster/dist/Cluster.js:110:19)
at async Function.launch (/app/node_modules/puppeteer-cluster/dist/Cluster.js:69:9)
at async Crawler.crawl (/app/crawler.js:552:20)
at async Crawler.run (/app/crawler.js:304:7)
Error: Command failed: crawl --url https://ipa2-f.kbc.be/particulieren/nl.html --limit 1 --generateWACZ --text --collection AEM
Crawl failed
Error: Unable to launch browser, error message: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1036745 is guaranteed to work.
at Cluster.init (/app/node_modules/puppeteer-cluster/dist/Cluster.js:110:19)
at async Function.launch (/app/node_modules/puppeteer-cluster/dist/Cluster.js:69:9)
at async Crawler.crawl (/app/crawler.js:552:20)
at async Crawler.run (/app/crawler.js:304:7)
at checkExecSyncError (node:child_process:828:11)
at execSync (node:child_process:899:15)
at executeCrawl (/opt/crawl-api/app.js:21804:3)
at /opt/crawl-api/app.js:21824:5
at Layer.handle [as handle_request] (/opt/crawl-api/app.js:16924:9)
at next (/opt/crawl-api/app.js:17093:17)
at Route.dispatch (/opt/crawl-api/app.js:17073:7)
at Layer.handle [as handle_request] (/opt/crawl-api/app.js:16924:9)
at /opt/crawl-api/app.js:17296:19`

Any idea's?

**Comment by edsu** [comment]
Can you share the configuration you are using to trigger the crawl and what environment it is running in? It looks Browsertrix Crawler is unable to start up Chromium, which is weird given that it should be installed via Docker.

**Comment by DriesVanbilloen** [comment]
The crawl comand that I used that generates this error:
`crawl --url <some-url> --limit 1 --collection test --text --generateWacz`

In the meantime I have found a possible solution that does work on my environment. With this command it does seem to work:
`crawl --url <some-url>--limit1 --collection test --text --generateWacz **--headless true**`
