### ISSUE TITLE
Can't create intranet profile

### ISSUE THREAD

**Issue by ArtHoff** [webrecorder/browsertrix-crawler#313]
Hi, I'm trying to create a login profile for one of our local SharePoint intranets but I run into this error:
`podman run -p 6080:6080 -p 9223:9223 -v $PWD/crawls/profiles:/crawls/profiles/ -it webrecorder/browsertrix-crawler create-login-profile --url "http://my.intranet.net/"`
{"logLevel":"debug","timestamp":"2023-05-17T07:59:39.244Z","context":"general","message":"Launching XVFB","details":{}}
{"logLevel":"info","timestamp":"2023-05-17T07:59:44.392Z","context":"general","message":"Loading page: http://my.intranet.net/","details":{}}
file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Frame.js:215
                    ? new Error(`${response.errorText} at ${url}`)
                      ^

Error: net::ERR_INVALID_AUTH_CREDENTIALS at http://my.intranet.net/
    at navigate (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Frame.js:215:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Frame.goto (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Frame.js:181:21)
    at async CDPPage.goto (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:435:16)
    at async main (file:///app/create-login-profile.js:207:3)

Node.js v18.15.0

When I go to the site in a web browser it comes up with the browser's inbuilt login screen. 
![image](https://github.com/webrecorder/browsertrix-crawler/assets/24282952/489e8ff6-14eb-4711-a2ad-631dd1cb6859)
Here I can login with my user ID and password.

I've also tried to create an interactive profile based on another site, once I was in the browser I navigated to my intranet site and logged in. I then saved the profile.
However when I then attempted to crawl the intranet with that profile I received an authentication error. The generated WACZ file just showed a blank white page.

Do you know what else I may need to do to scan such a site with browsertrix?
Thank you so much for any help you can offer.

**Comment by wvengen** [comment]
Idea for a workaround: did you try putting username and password in the URL?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#access_using_credentials_in_the_url

**Comment by robert-1043** [comment]
Sharepoint checks user rights for each element on the page.  I did a crawl with 2FA on mobile while creating the profile.  Replay however isn't great.  see #140 

Keep in mind: when using a certain user, Sharepoint gives access to everything the user has access to.  You might want to use another user than yourself with limited / broader rights.

**Comment by ArtHoff** [comment]
Thank you both for your suggestions. I had tried putting user name and password into the URL, but that didn't work for me.

I have now resorted to using cntlm proxy and with that I'm able to crawl the site.

I can see how it goes through the pages on the screencast port, but unfortunately it won't scroll and it won't write any warc files.

I'll log a different ticket for that.
