### ISSUE TITLE
Crawl stopping with TypeError: Headers.append:...is an invalid header value.

### ISSUE THREAD

**Issue by ldko** [webrecorder/browsertrix-crawler#607]
Running a recent crawl, I had the crawl error out with the message 
```
TypeError: Headers.append: "chunked
chunked" is an invalid header value.
```

Reproduce with:
`docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --url "https://rauli.cbs.dk/index.php/fsl/article/view/6151" --scopeType page  --generateWACZ --text --collection test`

Logs and error output:
```
{"timestamp":"2024-06-13T21:30:57.723Z","logLevel":"info","context":"general","message":"Browsertrix-Crawler 1.1.3 (with warcio.js 2.2.1)","details":{}}
{"timestamp":"2024-06-13T21:30:57.725Z","logLevel":"info","context":"general","message":"Seeds","details":[{"url":"https://rauli.cbs.dk/index.php/fsl/article/view/6151","scopeType":"page","include":[],"exclude":[],"allowHash":false,"depth":-1,"sitemap":null,"maxExtraHops":0,"maxDepth":0}]}
{"timestamp":"2024-06-13T21:30:58.318Z","logLevel":"info","context":"worker","message":"Creating 1 workers","details":{}}
{"timestamp":"2024-06-13T21:30:58.319Z","logLevel":"info","context":"worker","message":"Worker starting","details":{"workerid":0}}
{"timestamp":"2024-06-13T21:30:58.528Z","logLevel":"info","context":"worker","message":"Starting page","details":{"workerid":0,"page":"https://rauli.cbs.dk/index.php/fsl/article/view/6151"}}
{"timestamp":"2024-06-13T21:30:58.529Z","logLevel":"info","context":"crawlStatus","message":"Crawl statistics","details":{"crawled":0,"total":1,"pending":1,"failed":0,"limit":{"max":0,"hit":false},"pendingPages":["{\"seedId\":0,\"started\":\"2024-06-13T21:30:58.320Z\",\"extraHops\":0,\"url\":\"https:\\/\\/rauli.cbs.dk\\/index.php\\/fsl\\/article\\/view\\/6151\",\"added\":\"2024-06-13T21:30:57.797Z\",\"depth\":0}"]}}
{"timestamp":"2024-06-13T21:30:59.286Z","logLevel":"info","context":"general","message":"Awaiting page load","details":{"page":"https://rauli.cbs.dk/index.php/fsl/article/view/6151","workerid":0}}
node:internal/deps/undici/undici:1581
      return new TypeError(`${message.header}: ${message.message}`);
             ^

TypeError: Headers.append: "chunked
chunked" is an invalid header value.
    at webidl.errors.exception (node:internal/deps/undici/undici:1581:14)
    at webidl.errors.invalidArgument (node:internal/deps/undici/undici:1592:28)
    at _Headers.append (node:internal/deps/undici/undici:2098:31)
    at fill (node:internal/deps/undici/undici:1976:19)
    at new Headers (node:internal/deps/undici/undici:2081:11)
    at RequestResponseInfo.getMimeType (file:///app/dist/util/reqresp.js:199:25)
    at Recorder.addPageRecord (file:///app/dist/util/recorder.js:454:34)
    at Recorder.serializeToWARC (file:///app/dist/util/recorder.js:676:14)
    at Recorder.handleLoadingFinished (file:///app/dist/util/recorder.js:270:14)
    at file:///app/dist/util/recorder.js:77:60

Node.js v20.11.1
```

Requesting the URL in a browser, I see the response headers show `Transfer-Encoding: chunked` as a header included twice, so perhaps that is triggering the issue?:
```
HTTP/1.1 200 OK
Date: Thu, 13 Jun 2024 20:53:42 GMT
Server: Apache
Cache-Control: no-store
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
Keep-Alive: timeout=5, max=98
Connection: Keep-Alive
X-Via-NSCOPI: 1.0
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8
Set-Cookie: NSC_ESNS=0282d6e1-5c57-166b-9678-00e0edf4b04c_2075115191_0350719270_00000000004336986188; Path=/; Expires=Thu, 13-Jun-2024 20:53:57 GMT
Cache-Control: no-cache
Content-Encoding: gzip
Transfer-Encoding: chunked
```

**Comment by ikreymer** [comment]
thanks for the clear repro steps! Yes, i think somehow the double line caused it to be added with a newline. It's supposed to be escaped and replaced with newlines, but that was missing. The header is also rewritten so its actually stored as: 'x-orig-transfer-encoding: chunked, chunked`, since we don't want to use transfer-encoding at all.
Fixed in 1.1.4
