### ISSUE TITLE
'Browsertrix Profile Create" --> NameError 

### ISSUE THREAD

**Issue by ThomasPeetersKADOC** [webrecorder/browsertrix-crawler#65]
Hey everybody,

I've run into an issue with browsertrix. I've managed to install browsertrix itself but when I try to fire it up and create a profile to start crawling, I keep getting the following notice:

`Traceback (most recent call last):
  File "C:\Users\u0102607\AppData\Local\Programs\Python\Python39\lib\site-packages\docker-4.4.4-py3.9.egg\docker\api\client.py", line 159, in __init__
    self._custom_adapter = NpipeHTTPAdapter(
NameError: name 'NpipeHTTPAdapter' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\u0102607\AppData\Local\Programs\Python\Python39\Scripts\browsertrix-script.py", line 33, in <module>
    sys.exit(load_entry_point('browsertrix-cli==0.1.0.dev0', 'console_scripts', 'browsertrix')())
  File "C:\Users\u0102607\AppData\Local\Programs\Python\Python39\lib\site-packages\click-8.0.0a1-py3.9.egg\click\core.py", line 1025, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\u0102607\AppData\Local\Programs\Python\Python39\lib\site-packages\click-8.0.0a1-py3.9.egg\click\core.py", line 955, in main
    rv = self.invoke(ctx)
  File "C:\Users\u0102607\AppData\Local\Programs\Python\Python39\lib\site-packages\click-8.0.0a1-py3.9.egg\click\core.py", line 1517, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\u0102607\AppData\Local\Programs\Python\Python39\lib\site-packages\click-8.0.0a1-py3.9.egg\click\core.py", line 1514, in invoke
    super().invoke(ctx)
  File "C:\Users\u0102607\AppData\Local\Programs\Python\Python39\lib\site-packages\click-8.0.0a1-py3.9.egg\click\core.py", line 1279, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\u0102607\AppData\Local\Programs\Python\Python39\lib\site-packages\click-8.0.0a1-py3.9.egg\click\core.py", line 710, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\u0102607\AppData\Local\Programs\Python\Python39\lib\site-packages\browsertrix_cli-0.1.0.dev0-py3.9.egg\browsertrix_cli\profile.py", line 42, in profile
    docker_api = docker.from_env(version='auto')
  File "C:\Users\u0102607\AppData\Local\Programs\Python\Python39\lib\site-packages\docker-4.4.4-py3.9.egg\docker\client.py", line 96, in from_env
    return cls(
  File "C:\Users\u0102607\AppData\Local\Programs\Python\Python39\lib\site-packages\docker-4.4.4-py3.9.egg\docker\client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "C:\Users\u0102607\AppData\Local\Programs\Python\Python39\lib\site-packages\docker-4.4.4-py3.9.egg\docker\api\client.py", line 164, in __init__
    raise DockerException(
docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support`

The way I see it however, is that I've updated and installed everything necessary:
Pypiwin32 package is installed
pip 21.1.3 and python 3.9 is installed

Any idea's? Googling for the nameerror brings me to a similar issue with another application, the suggested fixes there don't resolve the problem for browsertrix.

Thanks in advance

**Comment by ikreymer** [comment]
This looks like a windows specific issue. Unfortunately, have not had a chance to try browsertrix-crawler on windows yet. Will update when there's a chance to look into this further. If anyone has access to windows and can test it, help definitely appreciate!

**Comment by robert-1043** [comment]
Was using Browsertrix with Ubuntu 18.04, have now installed Ubuntu 20.04 and Docker on a Windows 10 Enterprise 1909 laptop.  With this clean install no problem to get Browsertrix crawling using a profile.

However, I don't have a 'Python' folder inside
C:\Users\xxxxx\AppData\Local\Programs\

**Comment by ikreymer** [comment]
Closing, as likely won't be able to repro. Perhaps this is fixed with latest image, if there's a specific repro steps, feel free to comment.
