### ISSUE TITLE
Execution context was destroyed

### ISSUE THREAD

**Issue by rgaudin** [webrecorder/browsertrix-crawler#655]
Here's a crash log. In another issue, it's written that “Attempted to use detached Frame” warning is harmless but is it in this context? Any idead what's going on? 

```
[zimit::2024-07-26 05:21:46,337] INFO:Browsertrix crawler: version 1.2.5
[zimit::2024-07-26 05:21:46,358] INFO:Running browsertrix-crawler crawl: crawl --failOnFailedSeed --waitUntil load --depth -1 --timeout 90 --behaviors autoplay,autofetch,siteSpecific --behaviorTimeout 90 --sizeLimit 4294967296 --diskUtilization 90 --timeLimit 7200 --url https://www.d20pfsrd.com/ --userAgentSuffix zimit.kiwix.org+ contact+zimfarm@kiwix.org --mobileDevice Pixel 2 --cwd /output/.tmpwl_7osr1 --statsFilename /output/crawl.json
{"timestamp":"2024-07-26T05:21:50.126Z","logLevel":"info","context":"general","message":"Browsertrix-Crawler 1.2.5 (with warcio.js 2.2.1)","details":{}}
{"timestamp":"2024-07-26T05:21:50.133Z","logLevel":"info","context":"general","message":"Seeds","details":[{"url":"https://www.d20pfsrd.com/","scopeType":"prefix","include":["/^https?:\\/\\/www\\.d20pfsrd\\.com\\//"],"exclude":[],"allowHash":false,"depth":-1,"sitemap":null,"auth":null,"_authEncoded":null,"maxExtraHops":0,"maxDepth":1000000}]}
{"timestamp":"2024-07-26T05:21:50.134Z","logLevel":"info","context":"general","message":"Behavior Options","details":{"message":"{\"autoplay\":true,\"autofetch\":true,\"siteSpecific\":true,\"log\":\"__bx_log\",\"startEarly\":true}"}}
{"timestamp":"2024-07-26T05:21:53.929Z","logLevel":"info","context":"worker","message":"Creating 1 workers","details":{}}
{"timestamp":"2024-07-26T05:21:53.932Z","logLevel":"info","context":"worker","message":"Worker starting","details":{"workerid":0}}
{"timestamp":"2024-07-26T05:21:55.534Z","logLevel":"info","context":"worker","message":"Starting page","details":{"workerid":0,"page":"https://www.d20pfsrd.com/"}}
{"timestamp":"2024-07-26T05:21:55.543Z","logLevel":"info","context":"crawlStatus","message":"Crawl statistics","details":{"crawled":0,"total":1,"pending":1,"failed":0,"limit":{"max":0,"hit":false},"pendingPages":["{\"seedId\":0,\"started\":\"2024-07-26T05:21:53.940Z\",\"extraHops\":0,\"url\":\"https:\\/\\/www.d20pfsrd.com\\/\",\"added\":\"2024-07-26T05:21:50.455Z\",\"depth\":0}"]}}
{"timestamp":"2024-07-26T05:21:56.431Z","logLevel":"info","context":"general","message":"Awaiting page load","details":{"page":"https://www.d20pfsrd.com/","workerid":0}}
{"timestamp":"2024-07-26T05:22:10.875Z","logLevel":"info","context":"behavior","message":"Running behaviors","details":{"frames":2,"frameUrls":["https://www.d20pfsrd.com/","https://platform.twitter.com/widgets/widget_iframe.2f70fb173b9000da126c79afe2098f02.html?origin=https%3A%2F%2Fwww.d20pfsrd.com"],"page":"https://www.d20pfsrd.com/","workerid":0}}
{"timestamp":"2024-07-26T05:22:10.876Z","logLevel":"info","context":"behavior","message":"Run Script Started","details":{"frameUrl":"https://www.d20pfsrd.com/","page":"https://www.d20pfsrd.com/","workerid":0}}
{"timestamp":"2024-07-26T05:22:10.877Z","logLevel":"info","context":"behavior","message":"Run Script Started","details":{"frameUrl":"https://platform.twitter.com/widgets/widget_iframe.2f70fb173b9000da126c79afe2098f02.html?origin=https%3A%2F%2Fwww.d20pfsrd.com","page":"https://www.d20pfsrd.com/","workerid":0}}
[snip]
{"timestamp":"2024-07-26T06:18:18.044Z","logLevel":"warn","context":"behavior","message":"Waiting for custom page load failed","details":{"type":"exception","message":"Protocol error (Runtime.evaluate): Target closed","stack":"TargetCloseError: Protocol error (Runtime.evaluate): Target closed\n    at CallbackRegistry.clear (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:69:36)\n    at CdpCDPSession._onClosed (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:98:25)\n    at Connection.onMessage (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:127:25)\n    at WebSocket.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/node/NodeWebSocketTransport.js:38:32)\n    at callListener (/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)\n    at WebSocket.onMessage (/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:209:9)\n    at WebSocket.emit (node:events:519:28)\n    at Receiver.receiverOnMessage (/app/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:1220:20)\n    at Receiver.emit (node:events:519:28)\n    at Immediate.<anonymous> (/app/node_modules/puppeteer-core/node_modules/ws/lib/receiver.js:601:16)"}}
{"timestamp":"2024-07-26T06:18:18.070Z","logLevel":"warn","context":"links","message":"Link Extraction failed","details":{"type":"exception","message":"Attempted to use detached Frame '5727F00304B72AAF0B66B983FF03748F'.","stack":"Error: Attempted to use detached Frame '5727F00304B72AAF0B66B983FF03748F'.\n    at CdpFrame.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:92:23)\n    at file:///app/dist/crawler.js:1378:102\n    at Array.map (<anonymous>)\n    at Crawler.extractLinks (file:///app/dist/crawler.js:1378:72)\n    at Crawler.loadPage (file:///app/dist/crawler.js:1322:20)\n    at async Crawler.default [as driver] (file:///app/dist/defaultDriver.js:2:5)\n    at async Crawler.crawlPage (file:///app/dist/crawler.js:566:9)\n    at async PageWorker.crawlPage (file:///app/dist/util/worker.js:153:21)"}}
file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:72
            throw new Error('Execution context was destroyed');
                  ^

Error: Execution context was destroyed
    at file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:72:19
    at file:///app/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:1936:31
    at OperatorSubscriber2._this._next (file:///app/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:993:9)
    at Subscriber2.next (file:///app/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:696:12)
    at listener (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:365:24)
    at file:///app/node_modules/puppeteer-core/lib/esm/third_party/mitt/mitt.js:36:7
    at Array.map (<anonymous>)
    at Object.emit (file:///app/node_modules/puppeteer-core/lib/esm/third_party/mitt/mitt.js:35:20)
    at EventEmitter.emit (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/EventEmitter.js:77:23)
    at [nodejs.dispose] (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:151:23)

Node.js v20.15.0

```

**Comment by ikreymer** [comment]
The 'execution context destroyed' is usually an iframe that has been closed. Since we try to run behaviors in multiple iframes, there's no guarantee that an iframe won't be closed for whatever reason, and so waiting for behaviors to finish from that iframe will fail. However, it should not crash the entire crawler. It looks like that's what happened here?
Do you have the logs above that show what page this was on?

**Comment by rgaudin** [comment]
here's the full log
[0411ab50-2f72-4b8f-91a5-ace3228d871f_zimit(1).log](https://github.com/user-attachments/files/16424545/0411ab50-2f72-4b8f-91a5-ace3228d871f_zimit.1.log)

**Comment by ikreymer** [comment]
Tried a few different times, unable to repro this particular issue.

I would recommend for zimit to restart the crawler if it crashes - the crawl config logs are written and it should be possible to restart and pick up where it left off.

**Comment by rgaudin** [comment]
Understood.

We'll discuss the restart-on-crash strategy but beside the unconventionality, I have concerns regarding how the limits are implemented and we'll have to check how those are implemented.
