### ISSUE TITLE
WARC Record Write Failed

### ISSUE THREAD

**Issue by benoit74** [webrecorder/browsertrix-crawler#722]
This is a recent bug, happening only on 1.3.5 (1.3.4 is not affected).

Command:

```
docker run -v $PWD/output:/output --name crawlme --rm  webrecorder/browsertrix-crawler:1.3.5 crawl --failOnFailedSeed --behaviors "autoplay,autofetch,autoscroll" --url="https://www.radiozamaneh.com/" --mobileDevice "Pixel 2" --cwd /output --combineWARC
```

Logs:

```
{"timestamp":"2024-11-13T07:22:46.078Z","logLevel":"info","context":"general","message":"Browsertrix-Crawler 1.3.5 (with warcio.js 2.3.1)","details":{}}
{"timestamp":"2024-11-13T07:22:46.079Z","logLevel":"info","context":"general","message":"Seeds","details":[{"url":"https://www.radiozamaneh.com/","scopeType":"prefix","include":["/^https?:\\/\\/www\\.radiozamaneh\\.com\\//"],"exclude":[],"allowHash":false,"depth":-1,"sitemap":null,"auth":null,"_authEncoded":null,"maxExtraHops":0,"maxDepth":1000000}]}
{"timestamp":"2024-11-13T07:22:46.079Z","logLevel":"info","context":"general","message":"Behavior Options","details":{"message":"{\"autoplay\":true,\"autofetch\":true,\"autoscroll\":true,\"log\":\"__bx_log\",\"startEarly\":true}"}}
{"timestamp":"2024-11-13T07:22:46.407Z","logLevel":"info","context":"worker","message":"Creating 1 workers","details":{}}
{"timestamp":"2024-11-13T07:22:46.408Z","logLevel":"info","context":"worker","message":"Worker starting","details":{"workerid":0}}
{"timestamp":"2024-11-13T07:22:46.889Z","logLevel":"info","context":"worker","message":"Starting page","details":{"workerid":0,"page":"https://www.radiozamaneh.com/"}}
{"timestamp":"2024-11-13T07:22:46.890Z","logLevel":"info","context":"crawlStatus","message":"Crawl statistics","details":{"crawled":0,"total":1,"pending":1,"failed":0,"limit":{"max":0,"hit":false},"pendingPages":["{\"seedId\":0,\"started\":\"2024-11-13T07:22:46.409Z\",\"extraHops\":0,\"url\":\"https:\\/\\/www.radiozamaneh.com\\/\",\"added\":\"2024-11-13T07:22:46.112Z\",\"depth\":0}"]}}
{"timestamp":"2024-11-13T07:22:47.224Z","logLevel":"info","context":"general","message":"Awaiting page load","details":{"page":"https://www.radiozamaneh.com/","workerid":0}}
{"timestamp":"2024-11-13T07:22:47.399Z","logLevel":"warn","context":"recorder","message":"Skipping URL from unknown frame","details":{"url":"https://www.radiozamaneh.com/","frameId":"2ED39FB2DC308F9FC1F7ECF699743786"}}
{"timestamp":"2024-11-13T07:22:48.023Z","logLevel":"error","context":"writer","message":"WARC Record Write Failed","details":{"type":"exception","message":"Cannot convert argument to a ByteString because the character at index 126 has a value of 8224 which is greater than 255.","stack":"TypeError: Cannot convert argument to a ByteString because the character at index 126 has a value of 8224 which is greater than 255.\n    at webidl.converters.ByteString (node:internal/deps/undici/undici:3661:17)\n    at Object.record<ByteString, ByteString> (node:internal/deps/undici/undici:3568:32)\n    at webidl.converters.HeadersInit (node:internal/deps/undici/undici:8695:67)\n    at new Headers (node:internal/deps/undici/undici:8523:36)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:8:886)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:10:400)\n    at U.setField (file:///app/node_modules/warcio/dist/index.js:8:616)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:564)\n    at U.indexRecordPair (file:///app/node_modules/warcio/dist/index.js:8:2780)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:2358)"}}
{"timestamp":"2024-11-13T07:22:48.047Z","logLevel":"error","context":"writer","message":"WARC Record Write Failed","details":{"type":"exception","message":"Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.","stack":"TypeError: Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.\n    at webidl.converters.ByteString (node:internal/deps/undici/undici:3661:17)\n    at Object.record<ByteString, ByteString> (node:internal/deps/undici/undici:3568:32)\n    at webidl.converters.HeadersInit (node:internal/deps/undici/undici:8695:67)\n    at new Headers (node:internal/deps/undici/undici:8523:36)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:8:886)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:10:400)\n    at U.setField (file:///app/node_modules/warcio/dist/index.js:8:616)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:564)\n    at U.indexRecordPair (file:///app/node_modules/warcio/dist/index.js:8:2780)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:2358)"}}
{"timestamp":"2024-11-13T07:22:48.115Z","logLevel":"error","context":"writer","message":"WARC Record Write Failed","details":{"type":"exception","message":"Cannot convert argument to a ByteString because the character at index 126 has a value of 8224 which is greater than 255.","stack":"TypeError: Cannot convert argument to a ByteString because the character at index 126 has a value of 8224 which is greater than 255.\n    at webidl.converters.ByteString (node:internal/deps/undici/undici:3661:17)\n    at Object.record<ByteString, ByteString> (node:internal/deps/undici/undici:3568:32)\n    at webidl.converters.HeadersInit (node:internal/deps/undici/undici:8695:67)\n    at new Headers (node:internal/deps/undici/undici:8523:36)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:8:886)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:10:400)\n    at U.setField (file:///app/node_modules/warcio/dist/index.js:8:616)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:564)\n    at U.indexRecordPair (file:///app/node_modules/warcio/dist/index.js:8:2780)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:2358)"}}
{"timestamp":"2024-11-13T07:22:48.123Z","logLevel":"error","context":"writer","message":"WARC Record Write Failed","details":{"type":"exception","message":"Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.","stack":"TypeError: Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.\n    at webidl.converters.ByteString (node:internal/deps/undici/undici:3661:17)\n    at Object.record<ByteString, ByteString> (node:internal/deps/undici/undici:3568:32)\n    at webidl.converters.HeadersInit (node:internal/deps/undici/undici:8695:67)\n    at new Headers (node:internal/deps/undici/undici:8523:36)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:8:886)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:10:400)\n    at U.setField (file:///app/node_modules/warcio/dist/index.js:8:616)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:564)\n    at U.indexRecordPair (file:///app/node_modules/warcio/dist/index.js:8:2780)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:2358)"}}
{"timestamp":"2024-11-13T07:22:48.131Z","logLevel":"error","context":"writer","message":"WARC Record Write Failed","details":{"type":"exception","message":"Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.","stack":"TypeError: Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.\n    at webidl.converters.ByteString (node:internal/deps/undici/undici:3661:17)\n    at Object.record<ByteString, ByteString> (node:internal/deps/undici/undici:3568:32)\n    at webidl.converters.HeadersInit (node:internal/deps/undici/undici:8695:67)\n    at new Headers (node:internal/deps/undici/undici:8523:36)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:8:886)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:10:400)\n    at U.setField (file:///app/node_modules/warcio/dist/index.js:8:616)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:564)\n    at U.indexRecordPair (file:///app/node_modules/warcio/dist/index.js:8:2780)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:2358)"}}
{"timestamp":"2024-11-13T07:22:48.226Z","logLevel":"error","context":"writer","message":"WARC Record Write Failed","details":{"type":"exception","message":"Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.","stack":"TypeError: Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.\n    at webidl.converters.ByteString (node:internal/deps/undici/undici:3661:17)\n    at Object.record<ByteString, ByteString> (node:internal/deps/undici/undici:3568:32)\n    at webidl.converters.HeadersInit (node:internal/deps/undici/undici:8695:67)\n    at new Headers (node:internal/deps/undici/undici:8523:36)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:8:886)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:10:400)\n    at U.setField (file:///app/node_modules/warcio/dist/index.js:8:616)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:564)\n    at U.indexRecordPair (file:///app/node_modules/warcio/dist/index.js:8:2780)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:2358)"}}
{"timestamp":"2024-11-13T07:22:48.230Z","logLevel":"error","context":"writer","message":"WARC Record Write Failed","details":{"type":"exception","message":"Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.","stack":"TypeError: Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.\n    at webidl.converters.ByteString (node:internal/deps/undici/undici:3661:17)\n    at Object.record<ByteString, ByteString> (node:internal/deps/undici/undici:3568:32)\n    at webidl.converters.HeadersInit (node:internal/deps/undici/undici:8695:67)\n    at new Headers (node:internal/deps/undici/undici:8523:36)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:8:886)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:10:400)\n    at U.setField (file:///app/node_modules/warcio/dist/index.js:8:616)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:564)\n    at U.indexRecordPair (file:///app/node_modules/warcio/dist/index.js:8:2780)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:2358)"}}
{"timestamp":"2024-11-13T07:22:48.308Z","logLevel":"error","context":"writer","message":"WARC Record Write Failed","details":{"type":"exception","message":"Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.","stack":"TypeError: Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.\n    at webidl.converters.ByteString (node:internal/deps/undici/undici:3661:17)\n    at Object.record<ByteString, ByteString> (node:internal/deps/undici/undici:3568:32)\n    at webidl.converters.HeadersInit (node:internal/deps/undici/undici:8695:67)\n    at new Headers (node:internal/deps/undici/undici:8523:36)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:8:886)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:10:400)\n    at U.setField (file:///app/node_modules/warcio/dist/index.js:8:616)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:564)\n    at U.indexRecordPair (file:///app/node_modules/warcio/dist/index.js:8:2780)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:2358)"}}
{"timestamp":"2024-11-13T07:22:48.316Z","logLevel":"error","context":"writer","message":"WARC Record Write Failed","details":{"type":"exception","message":"Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.","stack":"TypeError: Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.\n    at webidl.converters.ByteString (node:internal/deps/undici/undici:3661:17)\n    at Object.record<ByteString, ByteString> (node:internal/deps/undici/undici:3568:32)\n    at webidl.converters.HeadersInit (node:internal/deps/undici/undici:8695:67)\n    at new Headers (node:internal/deps/undici/undici:8523:36)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:8:886)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:10:400)\n    at U.setField (file:///app/node_modules/warcio/dist/index.js:8:616)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:564)\n    at U.indexRecordPair (file:///app/node_modules/warcio/dist/index.js:8:2780)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:2358)"}}
{"timestamp":"2024-11-13T07:22:48.324Z","logLevel":"error","context":"writer","message":"WARC Record Write Failed","details":{"type":"exception","message":"Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.","stack":"TypeError: Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.\n    at webidl.converters.ByteString (node:internal/deps/undici/undici:3661:17)\n    at Object.record<ByteString, ByteString> (node:internal/deps/undici/undici:3568:32)\n    at webidl.converters.HeadersInit (node:internal/deps/undici/undici:8695:67)\n    at new Headers (node:internal/deps/undici/undici:8523:36)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:8:886)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:10:400)\n    at U.setField (file:///app/node_modules/warcio/dist/index.js:8:616)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:564)\n    at U.indexRecordPair (file:///app/node_modules/warcio/dist/index.js:8:2780)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:2358)"}}
{"timestamp":"2024-11-13T07:22:48.356Z","logLevel":"error","context":"writer","message":"WARC Record Write Failed","details":{"type":"exception","message":"Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.","stack":"TypeError: Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.\n    at webidl.converters.ByteString (node:internal/deps/undici/undici:3661:17)\n    at Object.record<ByteString, ByteString> (node:internal/deps/undici/undici:3568:32)\n    at webidl.converters.HeadersInit (node:internal/deps/undici/undici:8695:67)\n    at new Headers (node:internal/deps/undici/undici:8523:36)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:8:886)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:10:400)\n    at U.setField (file:///app/node_modules/warcio/dist/index.js:8:616)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:564)\n    at U.indexRecordPair (file:///app/node_modules/warcio/dist/index.js:8:2780)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:2358)"}}
{"timestamp":"2024-11-13T07:22:48.383Z","logLevel":"error","context":"writer","message":"WARC Record Write Failed","details":{"type":"exception","message":"Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.","stack":"TypeError: Cannot convert argument to a ByteString because the character at index 125 has a value of 1670 which is greater than 255.\n    at webidl.converters.ByteString (node:internal/deps/undici/undici:3661:17)\n    at Object.record<ByteString, ByteString> (node:internal/deps/undici/undici:3568:32)\n    at webidl.converters.HeadersInit (node:internal/deps/undici/undici:8695:67)\n    at new Headers (node:internal/deps/undici/undici:8523:36)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:8:886)\n    at U.getField (file:///app/node_modules/warcio/dist/index.js:10:400)\n    at U.setField (file:///app/node_modules/warcio/dist/index.js:8:616)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:564)\n    at U.indexRecordPair (file:///app/node_modules/warcio/dist/index.js:8:2780)\n    at U.indexRecord (file:///app/node_modules/warcio/dist/index.js:8:2358)"}}
```

Expected behavior: no such error about problems writing WARC record.

I don't get what changed between these two images ...

**Comment by ikreymer** [comment]
This was caused by cookie that had UTF-8 characters, that was not being serialized correctly when stored in x-wabac-preset-cookie header. The fix in 1.3.5 was temporary and the cookie is now stored in a different way, so should not happen in 1.4.0-beta.0 with warcio 2.4.0.

Additionally, the warcio 2.4.0 release also tests for this scenario now and avoids the issue, as it was happening during indexing where creating Headers isn't necessary (see linked commit [here](https://github.com/webrecorder/warcio.js/commit/3803f38af4c607fc4c8ca73138d6ded4eb35b520))
