### ISSUE TITLE
Headful interactive profile creation broken after v1.4.0 update

### ISSUE THREAD

**Issue by halvir** [webrecorder/browsertrix-crawler#726]
The headful interactive profile creation is not functional after updating Browsertrix-Crawler to version 1.4.0 release.
Error displayed on command line is following:

```
node:fs:448
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open '/app/node_modules/@novnc/novnc/core/rfb.js'
    at Object.readFileSync (node:fs:448:20)
    at InteractiveBrowser.handleRequest (file:///app/dist/create-login-profile.js:499:29)
    at Server.<anonymous> (file:///app/dist/create-login-profile.js:329:65)
    at Server.emit (node:events:518:28)
    at parserOnIncoming (node:_http_server:1141:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:118:17) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/node_modules/@novnc/novnc/core/rfb.js'
}

Node.js v20.18.1
```

Headless interactive profile creation seems to be working as intended.

**Comment by ikreymer** [comment]
Thanks for the report, novnc should not have been updated, will add a fix to pin it to 1.4.0 shortly.
